# Generated by Django 2.0.6 on 2018-06-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoCodeApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='status',
            new_name='code_status',
        ),
        migrations.RenameField(
            model_name='promocode',
            old_name='radius',
            new_name='radius_in_km',
        ),
    ]
